<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>SessionBookingService.Application</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SessionBookingService.WebApi" />
        <InternalsVisibleTo Include="SessionBookingService.Persistence" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\SessionBookingService.Domain\SessionBookingService.Domain.csproj" />
    </ItemGroup>
</Project>
