<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>SessionBookingService.Infrastructure</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="SessionBookingService.WebApi" />
    </ItemGroup>
</Project>
