using ClubAdministrationService.Domain.SubscriptionAggregate;

namespace ClubAdministrationService.Application.Subscriptions.Commands.CreateSubscription;

internal sealed record CreateSubscriptionCommand(SubscriptionType SubscriptionType, Guid AdminId);