<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Application</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Persistence" />
    </ItemGroup>
</Project>