<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ClubAdministrationService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <InternalsVisibleTo Include="ClubAdministrationService.UnitTests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>
</Project>
