<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SessionBookingService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="SessionBookingService.UnitTests" />
        <InternalsVisibleTo Include="SessionBookingService.Application" />
        <InternalsVisibleTo Include="SessionBookingService.Persistence" />
        <InternalsVisibleTo Include="SessionBookingService.Domain" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Ardalis.SmartEnum" />
    </ItemGroup>
</Project>
