<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SessionBookingService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="SessionBookingService.UnitTests" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="MediatR" />
    </ItemGroup>
</Project>
