<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SessionBookingService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj"/>
        <ProjectReference Include="../../../Analyzers/Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SessionBookingService.Tests.Unit"/>
        <InternalsVisibleTo Include="SessionBookingService.Application"/>
        <InternalsVisibleTo Include="SessionBookingService.Infrastructure"/>
        <InternalsVisibleTo Include="SessionBookingService.WebApi"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.SmartEnum"/>
        <PackageReference Include="Mediator.Abstractions"/>
    </ItemGroup>
</Project>
