<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <RootNamespace>SessionBookingService.WebApi</RootNamespace>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\SessionBookingService.Application\SessionBookingService.Application.csproj" />
      <ProjectReference Include="..\SessionBookingService.Contracts\SessionBookingService.Contracts.csproj" />
      <ProjectReference Include="..\SessionBookingService.Infrastructure\SessionBookingService.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Mediator.SourceGenerator">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    </ItemGroup>
</Project>
