<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SharedKernel</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="..\ServeSync.Domain\ServeSync.Domain.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="MediatR" />
    </ItemGroup>

</Project>
