<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>SharedKernel</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" />
      <PackageReference Include="Mediator.SourceGenerator" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="IntegrationEvents\ClubManagement\" />
    </ItemGroup>

</Project>
