<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SharedKernel</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Meziantou.Analyzer">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="..\ServeSync.Domain\ServeSync.Domain.csproj" />
    </ItemGroup>

</Project>
