<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>UserAdministrationService.Persistence</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="UserAdministrationService.WebApi" />
        <InternalsVisibleTo Include="UserAdministrationService.Infrastructure" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserAdministrationService.Application\UserAdministrationService.Application.csproj" />
      <ProjectReference Include="..\UserAdministrationService.Domain\UserAdministrationService.Domain.csproj" />
    </ItemGroup>
</Project>
