<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <RootNamespace>ClubAdministrationService.Persistence</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\ClubAdministrationService.Application\ClubAdministrationService.Application.csproj" />
      <ProjectReference Include="..\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Infrastructure" />
    </ItemGroup>
</Project>
