<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Persistence</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Application" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj" />
      <ProjectReference Include="..\ClubAdministrationService.Infrastructure\ClubAdministrationService.Infrastructure.csproj" />
    </ItemGroup>
</Project>
