<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <RootNamespace>ClubAdministrationService.Persistence</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\ClubAdministrationService.Application\ClubAdministrationService.Application.csproj" />
      <ProjectReference Include="..\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Infrastructure" />
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Integration" />
    </ItemGroup>
</Project>
