<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>SessionBookingService.Tests.Integration</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DotNet.Testcontainers"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing"/>
        <PackageReference Include="Testcontainers"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\SessionBookingService.WebApi\SessionBookingService.WebApi.csproj"/>
        <ProjectReference Include="..\..\src\SessionBookingService.Domain\SessionBookingService.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../../Analyzers/Analyzers/Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../../../Analyzers/Analyzers.CodeFix/Analyzers.CodeFix.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
