<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Integration" />
    </ItemGroup>
</Project>
