<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Tests.Unit</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Unit"/>
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Integration"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../../Analyzers/Analyzers/Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../../../Analyzers/Analyzers.CodeFix/Analyzers.CodeFix.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
