<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SessionReservationService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="SessionReservationService.UnitTests" />
    </ItemGroup>
</Project>
