<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>UserAdministrationService.Domain</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="UserAdministrationService.Application" />
        <InternalsVisibleTo Include="UserAdministrationService.Persistence" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" />
    </ItemGroup>
</Project>
