<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>UserAdministrationService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="UserAdministrationService.Application"/>
        <InternalsVisibleTo Include="UserAdministrationService.Persistence"/>
        <InternalsVisibleTo Include="UserAdministrationService.Infrastructure"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Interfaces\"/>
    </ItemGroup>
</Project>
