// <auto-generated />
using System;
using ClubAdministrationService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubAdministrationService.Infrastructure.Migrations
{
    [DbContext(typeof(ClubDbContext))]
    [Migration("20260803172224_AddOutboxIntegrationEvents")]
    partial class AddOutboxIntegrationEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubAdministrationService.Domain.AdminAggregate.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ClubAdministrationService.Domain.ClubAggregate.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("_courtIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CourtIds");

                    b.Property<string>("_instructorIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("InstructorIds");

                    b.Property<int>("_maxCourtCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("MaxCourtCapacity");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ClubAdministrationService.Domain.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("integer");

                    b.Property<string>("_clubIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ClubIds");

                    b.Property<int>("_maxCourtsAllowed")
                        .HasColumnType("integer")
                        .HasColumnName("MaxCourtsAllowed");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ClubAdministrationService.Infrastructure.IntegrationEvents.OutboxIntegrationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxIntegrationEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
