<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.SmartEnum" />
      <PackageReference Include="MediatR" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi" />
        <InternalsVisibleTo Include="ClubAdministrationService.Application" />
        <InternalsVisibleTo Include="ClubAdministrationService.Persistence" />
        <InternalsVisibleTo Include="ClubAdministrationService.UnitTests" />
        <InternalsVisibleTo Include="ClubAdministrationService.IntegrationTests" />
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Data" />
    </ItemGroup>
</Project>
