<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.SmartEnum" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.Application" />
    </ItemGroup>
</Project>
