<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.Infrastructure</RootNamespace>
        <NoWarn>$(NoWarn);MA0048;IDE0161</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.VisualStudio.Threading"/>
        <PackageReference Include="RabbitMQ.Client"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Mediator.Abstractions"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ClubAdministrationService.WebApi"/>
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Integration"/>
        <InternalsVisibleTo Include="ClubAdministrationService.Tests.Architecture"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ClubAdministrationService.Application\ClubAdministrationService.Application.csproj"/>
        <ProjectReference Include="..\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj"/>
        <ProjectReference Include="../../../Analyzers/Analyzers/Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../../../Analyzers/Analyzers.CodeFix/Analyzers.CodeFix.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Migrations\"/>
    </ItemGroup>
</Project>
