<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>ClubAdministrationService.Tests.Unit</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\ClubAdministrationService.Domain\ClubAdministrationService.Domain.csproj"/>
        <ProjectReference Include="..\ClubAdministrationService.Tests.Data\ClubAdministrationService.Tests.Data.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../../Analyzers/Analyzers/Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../../../Analyzers/Analyzers.CodeFix/Analyzers.CodeFix.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Application\"/>
    </ItemGroup>
</Project>
