<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <RootNamespace>ClubAdministrationService.WebApi</RootNamespace>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\ClubAdministrationService.Contracts\ClubAdministrationService.Contracts.csproj" />
      <ProjectReference Include="..\ClubAdministrationService.Application\ClubAdministrationService.Application.csproj" />
      <ProjectReference Include="..\ClubAdministrationService.Infrastructure\ClubAdministrationService.Infrastructure.csproj" />
    </ItemGroup>
</Project>
