// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SessionBookingService.Infrastructure;

#nullable disable

namespace SessionBookingService.Infrastructure.Migrations
{
    [DbContext(typeof(SessionBookingDbContext))]
    [Migration("20260622151508_AddInitialDataModel")]
    partial class AddInitialDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SessionBookingService.Domain.CourtsAggregate.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("_maxDailySessions")
                        .HasColumnType("integer")
                        .HasColumnName("MaxDailySessions");

                    b.Property<string>("_sessionIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SessionIds");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("SessionBookingService.Domain.InstructorAggregate.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("_sessionIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SessionIds");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("SessionBookingService.Domain.PlayerAggregate.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("_sessionIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SessionIds");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SessionBookingService.Domain.SessionAggregate.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayerCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SessionBookingService.Domain.CourtsAggregate.Court", b =>
                {
                    b.OwnsOne("SharedKernel.Schedule", "_schedule", b1 =>
                        {
                            b1.Property<Guid>("CourtId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ScheduleId");

                            b1.Property<string>("_calendar")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ScheduleCalendar");

                            b1.HasKey("CourtId");

                            b1.ToTable("Courts");

                            b1.WithOwner()
                                .HasForeignKey("CourtId");
                        });

                    b.Navigation("_schedule");
                });

            modelBuilder.Entity("SessionBookingService.Domain.InstructorAggregate.Instructor", b =>
                {
                    b.OwnsOne("SharedKernel.Schedule", "_schedule", b1 =>
                        {
                            b1.Property<Guid>("InstructorId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ScheduleId");

                            b1.Property<string>("_calendar")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ScheduleCalendar");

                            b1.HasKey("InstructorId");

                            b1.ToTable("Instructors");

                            b1.WithOwner()
                                .HasForeignKey("InstructorId");
                        });

                    b.Navigation("_schedule");
                });

            modelBuilder.Entity("SessionBookingService.Domain.PlayerAggregate.Player", b =>
                {
                    b.OwnsOne("SharedKernel.Schedule", "_schedule", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ScheduleId");

                            b1.Property<string>("_calendar")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ScheduleCalender");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("_schedule");
                });

            modelBuilder.Entity("SessionBookingService.Domain.SessionAggregate.Session", b =>
                {
                    b.OwnsMany("SessionBookingService.Domain.SessionAggregate.Booking", "_bookings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("SessionBookings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("SessionBookingService.Domain.SessionAggregate.SessionCategory", "Categories", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("SessionCategories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("SharedKernel.TimeSlot", "Time", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Categories");

                    b.Navigation("Time")
                        .IsRequired();

                    b.Navigation("_bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
