<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>UserAdministrationService.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserAdministrationService.Domain\UserAdministrationService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Mediator.SourceGenerator">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="UserAdministrationService.WebApi" />
        <InternalsVisibleTo Include="UserAdministrationService.Persistence" />
        <InternalsVisibleTo Include="UserAdministrationService.Infrastructure" />
    </ItemGroup>
</Project>
