@api_host = http://localhost:5245

### Create Order
POST {{api_host}}/orders
Content-Type: application/json
Accept: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": 1,
      "quantity": 1,
      "price": 1.0
    }
  ]
}