<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>SessionBookingService.UnitTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\" />
      <Folder Include="Domain\PlayerAggregate\" />
      <Folder Include="Domain\TestsConstants\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\SessionBookingService.Domain\SessionBookingService.Domain.csproj" />
    </ItemGroup>

</Project>
